/**
 * Sample parish records used by `npm run db:demo`.
 *
 * Chosen to exercise the admin panel rather than to be exhaustive: both
 * statuses, several GKKs, every sacrament, a spread of ages and blood types,
 * and members with and without ministry assignments — so the dashboard charts
 * and every filter have something to show.
 *
 * Names and addresses are fictional.
 */

export const DEMO_HOUSEHOLDS = [
  {
    householdName: 'Dela Cruz Family',
    street: '24 Rizal St.',
    barangay: 'Purok 3, Mua-an',
    city: 'Kidapawan City',
    province: 'North Cotabato',
    zip: '9400',
    contact: '0917 555 0142',
    email: 'delacruz.family@example.com',
    gkk: 'GKK San Isidro',
    familyGrouping: 'Grouping 1',
    status: 'Verified',
    volunteer: 'Yes',
    notifyOptin: true,
    members: [
      {
        firstName: 'Juan', middleName: 'Santos', lastName: 'Dela Cruz',
        relationship: 'Head of Household', sex: 'Male', dob: '1981-06-14',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Married',
        contact: '0917 555 0142', email: 'juan.delacruz@example.com',
        occupation: 'Farmer', bloodType: 'O+',
        hasBaptism: true, baptismDate: '1981-08-02', baptismChurch: 'Our Lady of Guadalupe',
        hasCommunion: true, communionDate: '1990-05-13', communionChurch: 'Our Lady of Guadalupe',
        hasConfirmation: true, confDate: '1995-11-19', confChurch: 'Our Lady of Guadalupe',
        confName: 'Juan Diego', confSponsor: 'Ramon Alvarez',
        hasMatrimony: true, matDate: '2006-02-11', matChurch: 'Our Lady of Guadalupe', matType: 'Catholic',
        ministries: ['Lector & Commentator'], organizations: ['Parish Pastoral Council'],
      },
      {
        firstName: 'Maria', middleName: 'Bautista', lastName: 'Dela Cruz',
        relationship: 'Spouse', sex: 'Female', dob: '1984-09-30',
        placeOfBirth: 'Davao City', civilStatus: 'Married',
        contact: '0918 555 0143', occupation: 'Teacher', bloodType: 'A+',
        hasBaptism: true, baptismDate: '1984-11-11', baptismChurch: 'San Pedro Cathedral',
        hasCommunion: true, communionDate: '1993-05-09', communionChurch: 'San Pedro Cathedral',
        hasConfirmation: true, confDate: '1998-10-25', confChurch: 'San Pedro Cathedral',
        confName: 'Maria Teresa', confSponsor: 'Lourdes Yap',
        hasMatrimony: true, matDate: '2006-02-11', matChurch: 'Our Lady of Guadalupe', matType: 'Catholic',
        ministries: ['Choir', 'Catechist'], organizations: ["Catholic Women's League"],
      },
      {
        firstName: 'Miguel', middleName: 'Bautista', lastName: 'Dela Cruz',
        relationship: 'Son', sex: 'Male', dob: '2008-03-22',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single', bloodType: 'O+',
        hasBaptism: true, baptismDate: '2008-05-18', baptismChurch: 'Our Lady of Guadalupe',
        hasCommunion: true, communionDate: '2017-05-14', communionChurch: 'Our Lady of Guadalupe',
        ministries: ['Altar Servers'], organizations: ['Youth Ministry'],
      },
      {
        firstName: 'Sofia', middleName: 'Bautista', lastName: 'Dela Cruz',
        relationship: 'Daughter', sex: 'Female', dob: '2014-12-05',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single', bloodType: 'A+',
        hasBaptism: true, baptismDate: '2015-02-08', baptismChurch: 'Our Lady of Guadalupe',
      },
    ],
  },
  {
    householdName: 'Reyes Family',
    street: '5 Bonifacio St.',
    barangay: 'Purok 2, Mua-an',
    city: 'Kidapawan City',
    province: 'North Cotabato',
    zip: '9400',
    contact: '0920 555 0177',
    email: '',
    gkk: 'GKK San Isidro',
    familyGrouping: 'Grouping 2',
    status: 'Pending',
    volunteer: 'Maybe',
    notifyOptin: false,
    members: [
      {
        firstName: 'Ana', middleName: 'Villanueva', lastName: 'Reyes',
        relationship: 'Head of Household', sex: 'Female', dob: '1969-04-08',
        placeOfBirth: 'Cotabato City', civilStatus: 'Widowed',
        contact: '0920 555 0177', occupation: 'Sari-sari store owner', bloodType: 'B+',
        hasBaptism: true, baptismDate: '1969-06-15', baptismChurch: 'Immaculate Conception',
        hasCommunion: true, communionDate: '1978-05-07', communionChurch: 'Immaculate Conception',
        hasConfirmation: true, confDate: '1983-09-11', confChurch: 'Immaculate Conception',
        confName: 'Ana Maria', confSponsor: 'Corazon Lim',
        hasMatrimony: true, matDate: '1994-01-29', matChurch: 'Immaculate Conception', matType: 'Catholic',
        ministries: ['Choir'], organizations: ['Legion of Mary'],
      },
      {
        firstName: 'Cora', middleName: 'Villanueva', lastName: 'Reyes',
        relationship: 'Daughter', sex: 'Female', dob: '2000-07-19',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single',
        email: 'cora.reyes@example.com', occupation: 'Nurse', bloodType: 'B+',
        hasBaptism: true, baptismDate: '2000-09-24', baptismChurch: 'Our Lady of Guadalupe',
        hasCommunion: true, communionDate: '2009-05-10', communionChurch: 'Our Lady of Guadalupe',
        hasConfirmation: true, confDate: '2014-11-23', confChurch: 'Our Lady of Guadalupe',
        confName: 'Cora Immaculada', confSponsor: 'Nenita Reyes',
        organizations: ['Youth Ministry'],
      },
      {
        firstName: 'Ben', middleName: 'Villanueva', lastName: 'Reyes',
        relationship: 'Son', sex: 'Male', dob: '2014-10-02',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single', bloodType: 'O-',
        hasBaptism: true, baptismDate: '2014-12-14', baptismChurch: 'Our Lady of Guadalupe',
      },
    ],
  },
  {
    householdName: 'Santos Family',
    street: '10 Mabini St.',
    barangay: 'Purok 1, Mua-an',
    city: 'Kidapawan City',
    province: 'North Cotabato',
    zip: '9400',
    contact: '0905 555 0198',
    email: 'santos.home@example.com',
    gkk: 'GKK San Lorenzo Ruiz',
    familyGrouping: 'Grouping 1',
    status: 'Verified',
    volunteer: 'Yes',
    notifyOptin: true,
    members: [
      {
        firstName: 'Ramon', middleName: 'Cruz', lastName: 'Santos',
        relationship: 'Head of Household', sex: 'Male', dob: '1956-11-27',
        placeOfBirth: 'Iloilo City', civilStatus: 'Married',
        contact: '0905 555 0198', occupation: 'Retired teacher', bloodType: 'AB+',
        hasBaptism: true, baptismDate: '1957-01-20', baptismChurch: 'Jaro Cathedral',
        hasCommunion: true, communionDate: '1965-05-02', communionChurch: 'Jaro Cathedral',
        hasConfirmation: true, confDate: '1970-08-16', confChurch: 'Jaro Cathedral',
        confName: 'Ramon Pio', confSponsor: 'Eduardo Sison',
        hasMatrimony: true, matDate: '1982-05-08', matChurch: 'Jaro Cathedral', matType: 'Catholic',
        ministries: ['Sacristan / Money Counters'], organizations: ['Knights of Columbus', 'Parish Pastoral Council'],
      },
      {
        firstName: 'Elena', middleName: 'Gomez', lastName: 'Santos',
        relationship: 'Spouse', sex: 'Female', dob: '1960-02-14',
        placeOfBirth: 'Iloilo City', civilStatus: 'Married',
        occupation: 'Retired midwife', bloodType: 'A-',
        hasBaptism: true, baptismDate: '1960-04-03', baptismChurch: 'Jaro Cathedral',
        hasCommunion: true, communionDate: '1968-05-05', communionChurch: 'Jaro Cathedral',
        hasConfirmation: true, confDate: '1973-09-09', confChurch: 'Jaro Cathedral',
        confName: 'Elena Lourdes', confSponsor: 'Remedios Tan',
        hasMatrimony: true, matDate: '1982-05-08', matChurch: 'Jaro Cathedral', matType: 'Catholic',
        ministries: ['Kaabag'], organizations: ["Catholic Women's League", 'Legion of Mary'],
      },
    ],
  },
  {
    householdName: 'Mendoza Family',
    street: '78 Quezon Ave.',
    barangay: 'Purok 5, Mua-an',
    city: 'Kidapawan City',
    province: 'North Cotabato',
    zip: '9400',
    contact: '0947 555 0211',
    email: '',
    gkk: 'GKK San Pedro Calungsod',
    familyGrouping: 'Grouping 3',
    status: 'Pending',
    volunteer: 'No',
    notifyOptin: false,
    members: [
      {
        firstName: 'Ricardo', middleName: 'Uy', lastName: 'Mendoza',
        relationship: 'Head of Household', sex: 'Male', dob: '1990-01-09',
        placeOfBirth: 'General Santos City', civilStatus: 'Separated',
        contact: '0947 555 0211', occupation: 'Tricycle driver', bloodType: 'O+',
        hasBaptism: true, baptismDate: '1990-03-25', baptismChurch: 'Sto. Niño Parish',
        hasCommunion: true, communionDate: '1999-05-16', communionChurch: 'Sto. Niño Parish',
      },
      {
        firstName: 'Liza', middleName: 'Uy', lastName: 'Mendoza',
        relationship: 'Daughter', sex: 'Female', dob: '2012-06-21',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single',
        hasBaptism: true, baptismDate: '2012-08-19', baptismChurch: 'Our Lady of Guadalupe',
        hasCommunion: true, communionDate: '2021-05-09', communionChurch: 'Our Lady of Guadalupe',
        ministries: ['Altar Servers'],
      },
    ],
  },
  {
    householdName: 'Tan Family',
    street: '3 Aguinaldo Ext.',
    barangay: 'Purok 4, Mua-an',
    city: 'Kidapawan City',
    province: 'North Cotabato',
    zip: '9400',
    contact: '0936 555 0264',
    email: 'tanfamily@example.com',
    gkk: 'GKK Sto. Niño',
    familyGrouping: 'Grouping 4',
    status: 'Verified',
    volunteer: 'Maybe',
    notifyOptin: true,
    members: [
      {
        firstName: 'Grace', middleName: 'Lim', lastName: 'Tan',
        relationship: 'Head of Household', sex: 'Female', dob: '1978-08-03',
        placeOfBirth: 'Cebu City', civilStatus: 'Married',
        contact: '0936 555 0264', email: 'grace.tan@example.com',
        occupation: 'Accountant', bloodType: 'AB-',
        hasBaptism: true, baptismDate: '1978-10-15', baptismChurch: 'Sto. Niño Basilica',
        hasCommunion: true, communionDate: '1987-05-03', communionChurch: 'Sto. Niño Basilica',
        hasConfirmation: true, confDate: '1992-10-04', confChurch: 'Sto. Niño Basilica',
        confName: 'Grace Cecilia', confSponsor: 'Imelda Ong',
        hasMatrimony: true, matDate: '2004-12-18', matChurch: 'Sto. Niño Basilica', matType: 'Convalidation',
        ministries: ['Ushers & Collectors'], organizations: ['Couples for Christ (CFC)'],
      },
      {
        firstName: 'Peter', middleName: 'Go', lastName: 'Tan',
        relationship: 'Spouse', sex: 'Male', dob: '1975-05-16',
        placeOfBirth: 'Cebu City', civilStatus: 'Married',
        occupation: 'Hardware supplier', bloodType: 'B-',
        hasBaptism: true, baptismDate: '1975-07-27', baptismChurch: 'Sto. Niño Basilica',
        hasCommunion: true, communionDate: '1984-05-06', communionChurch: 'Sto. Niño Basilica',
        hasConfirmation: true, confDate: '1989-09-24', confChurch: 'Sto. Niño Basilica',
        confName: 'Peter Paul', confSponsor: 'Alfonso Chua',
        hasMatrimony: true, matDate: '2004-12-18', matChurch: 'Sto. Niño Basilica', matType: 'Convalidation',
        organizations: ['Couples for Christ (CFC)', 'Knights of Columbus'],
      },
      {
        firstName: 'Andrea', middleName: 'Lim', lastName: 'Tan',
        relationship: 'Daughter', sex: 'Female', dob: '2006-09-11',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single',
        email: 'andrea.tan@example.com', bloodType: 'AB-',
        hasBaptism: true, baptismDate: '2006-11-19', baptismChurch: 'Our Lady of Guadalupe',
        hasCommunion: true, communionDate: '2015-05-10', communionChurch: 'Our Lady of Guadalupe',
        hasConfirmation: true, confDate: '2020-11-22', confChurch: 'Our Lady of Guadalupe',
        confName: 'Andrea Faustina', confSponsor: 'Grace Ong',
        ministries: ['Choir'], organizations: ['Youth Ministry'],
      },
    ],
  },
  {
    householdName: 'Bautista Family',
    street: '41 Del Pilar St.',
    barangay: 'Purok 6, Mua-an',
    city: 'Kidapawan City',
    province: 'North Cotabato',
    zip: '9400',
    contact: '',
    email: '',
    gkk: 'GKK San Lorenzo Ruiz',
    familyGrouping: 'Grouping 2',
    status: 'Pending',
    volunteer: '',
    notifyOptin: false,
    members: [
      {
        firstName: 'Teresita', middleName: '', lastName: 'Bautista',
        relationship: 'Head of Household', sex: 'Female', dob: '1948-10-01',
        placeOfBirth: 'Kabankalan City', civilStatus: 'Widowed',
        occupation: 'Retired', bloodType: 'O+',
        hasBaptism: true, baptismDate: '1948-12-12', baptismChurch: 'St. Francis Xavier',
        hasCommunion: true, communionDate: '1957-05-05', communionChurch: 'St. Francis Xavier',
        hasConfirmation: true, confDate: '1962-08-19', confChurch: 'St. Francis Xavier',
        confName: 'Teresita del Rosario', confSponsor: 'Pilar Montenegro',
        hasMatrimony: true, matDate: '1971-06-12', matChurch: 'St. Francis Xavier', matType: 'Catholic',
        ministries: ['Kaabag'], organizations: ['Legion of Mary'],
      },
      {
        firstName: 'Noel', middleName: 'Reyes', lastName: 'Bautista',
        relationship: 'Son', sex: 'Male', dob: '1996-03-30',
        placeOfBirth: 'Kidapawan City', civilStatus: 'Single',
        occupation: 'Carpenter', bloodType: 'A+',
        hasBaptism: true, baptismDate: '1996-06-02', baptismChurch: 'Our Lady of Guadalupe',
        hasCommunion: true, communionDate: '2005-05-08', communionChurch: 'Our Lady of Guadalupe',
        ministries: ['Sacristan / Money Counters'],
      },
    ],
  },
];
